.travis.yml
package.json

* chore(coverage): use mocha instead of npm test
* chore(test): simplify test command
* chore(build): ignore *.test.js during transpilation

updated npm scripts for coverage, test & build

---

src/properties/output/index.js
src/properties/output/index.test.js

I just learned that this is a thing. Undocumented unfortunately. This is probably not the last time that we'll have to add undocumented properties.

fix(output): Add hashDigestLength

---

package.json

I noticed this was missing when testing out Node 0.10.0 with the [failed build](https://travis-ci.org/jonathanewerner/webpack-validator/jobs/122553121) which uses `npm@2`. We use glob [here](https://github.com/jonathanewerner/webpack-validator/blob/1dd1d8ba6d824324bff6bdd2252a8b63717ee6c2/test/passing-configs/index.js)

test(deps): Add missing `glob` dependency

---

README.md
package.json
src/index.js
src/index.test.js
test/utils/allInvalid.js
test/utils/allValid.js

I integrated @nyrosmith's improved version of the `validate` function (it shows all validation results, not just the first) and added an option to the validate function, see updated `README.md` for description.
What do you think?

feat: add `returnValidation` option to validate()

---

README.md
src/bin/webpack-validator.js
src/index.js
src/index.test.js

I added support for `quiet` mode.
As I had some trouble with `npm link`, it would be good if you could have a look at the cli side. It should work but better to be safe than sure. It also insisted on rewriting the whole bin file (encoding or file ending problem?).
Closes #69.

Quiet mode

---

src/properties/devServer/index.js
src/properties/devServer/index.test.js

Webpack defines a few stats presets accessible through a string. Better allow those.
See https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/Stats.js#L696-L730 and https://github.com/webpack/webpack/issues/1191 for further information.

feat(webpack-dev-server): Support `stats` presets

---

src/properties/devServer/index.js
src/properties/devServer/index.test.js

As documented at https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option .
Closes #82.

feat(webpack-dev-server): Support object for `historyApiFallback`

---

README.md
package.json
src/bin/script-parsers.js
src/bin/script-parsers.test.js
src/bin/validate-all-scripts.js
src/bin/validate-config.js
src/bin/webpack-validator.js

Now it's possible to execute `webpack-validator --all-scripts` (or just `-a`). After executing, *webpack-validator* will go through your **package.json** `scripts` and tries to validate each.
Closes #72.

feat(cli): Support `--all-scripts`

---

package.json
src/bin/validate-config.js

In webpack 2, your config can be a function that accepts the `env` flag
as parsed from [yargs][yargs] (see [here][webpack-usage]). This will
allow people to use the --env flag with the CLI for their Webpack 2
configs.
[yargs]: https://github.com/yargs/yargs
[webpack-usage]: https://github.com/webpack/webpack/blob/76e845914b5ff18de8d13a9c188666a60c736fd0/bin/convert-argv.js#L103

feat(cli): Support webpack 2 --env

---

src/properties/context/index.test.js
src/properties/devServer/index.test.js
src/properties/devtool/index.test.js
src/properties/entry/index.test.js
src/properties/externals/index.test.js
src/properties/module/index.test.js
src/properties/node/index.test.js
src/properties/output/index.test.js
src/properties/plugins/index.test.js
src/properties/resolve/index.test.js
src/properties/target/index.test.js
src/properties/watchOptions/index.test.js
test/utils/allInvalid.js
test/utils/allValid.js

This is inspired by a comment from @bebraw asking why we need those "#<number" comments all over the place. The reason for this is that the test utils `allValid` and `allInvalid` create test case descriptions (`it("...")`) by using the array index of the given case. In order to find a failing test case, the comments would be necessary. It's kinda awkward. So what about the putting the whole stringified config slice into the test description, like this:
What do you think? I'd like this as it's cumbersome to shift test cases around, forcing you to change the numbering each time. This implementation is much clearer I think.
If you like it, i'll remove the number comments before we merge this PR.

test: improve testing utils

---

README.md

fix: adapt validate() examples to v2 api

---

CONTRIBUTING.md
README.md
package.json
src/index.js
src/properties/module/index.js
src/properties/module/index.test.js

Implements #38. Two opt-in rules for having stricter "best-practice" validations for loader include/exclude options. See README for explanation.
cc @bebraw as you brought this issue up. :)

Opt-in rules for loader include/exclude

---

src/properties/output/index.js
src/properties/output/index.test.js
src/types/absolutePath.js
src/types/index.js

Fixes #102. I'll merge this right away as it breaks our build process at work as well. :D

fix(output.path): do not check output.path for file existence

---

src/index.js

These don't actually have to exist before webpack runs. If they don't then webpack will behave like they aren't there and just create the `recordsPath`/`recordsOutputPath` when it's done.

fix(recordsPath): records paths do not have to currently exist

---

src/properties/devtool/index.js
src/properties/devtool/index.test.js

Add missing webpack devtool combinations i.e. #cheap-module-eval-inline-source-map

fix(devtool): add missing devtool options #113

---

src/bin/validate-config.js
src/index.js
src/index.test.js
test/passing-configs/webpack-multi-compiler.js
test/utils/allInvalid.js
test/utils/allValid.js

when provided with an array of configurations, iterate array and validate each configuration
individually
fixes #117

fix: support webpack multi-compiler

---

src/index.js
src/index.test.js

Default option object to keep caller from having to pass empty object during function invocation when using CJS-based library import.
functionality impacts: none known

fix: Set default empty object for validate options

---

src/properties/module/index.js
src/properties/module/index.test.js

Before:
This resulted in an error:
```js
loaders: [
test: /\.js$/,
loaders: [
{ // Can't use object here
loader: 'babel',
query: {
presets: ['es2015']
}
}
]
]
```
This did not:
```js
loaders: [
test: /\.js$/,
loaders: [
'babel?presets[]=es2015'
]
]
```
This PR makes it so that both strings and objects are allowed in the `loaders` array inside loader.

Allow mix of objects and strings in `loaders[i].loaders` array. Fixes #124.

---

src/properties/devtool/index.js
src/properties/devtool/index.test.js
test/utils/allValid.js

In webpack config it's also possible to disable sourcemaps by providing `false` to `devtool`. It's also a default value: https://github.com/webpack/webpack/blob/40aac864fd88495cd56dbec9bab522f8f34a47ea/lib/WebpackOptionsDefaulter.js#L11
It's useful, for example for this:
```js
{
devtool: isProd ? false : 'eval'
}
```
This PR adds `false` as a valid value for `devtool`.

Allow `false` as "devtool" value

---

package.json

Old version of cross-env brings transitively lodash.assign which is deprecated and causes warning during `npm install` (both on this project and on all projects using webpack-validator)
```
$ npm install
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
```

cross-env upgraded

---

.gitignore
src/properties/devServer/index.js
src/properties/devServer/index.test.js

Add missing setup property to devServer options.
See https://webpack.github.io/docs/webpack-dev-server.html#api for setup
option
Close #143

fix(devServer): add setup property to devServer options

---

src/index.js
src/properties/performance/index.js
src/properties/performance/index.test.js

Webpack 2.1.0-beta.28 adds `performance.hints` (which take boolean values) as a way to enable/disable performance warnings. (The first performance warning is about bundle size.)

feat: Allow performance.hints in webpack config
